-include ./configs/$(TARGET_PLATFORM_NAME)-variables.mk


LIBVORBIS_NAME := libvorbis
LIBVORBIS_PKG := src/$(LIBVORBIS_NAME)-$(LIBVORBIS_VERSION).tar.xz

LIBVORBIS_TARGET_BUILD_DIR := $(PLATFORM_BUILD_DIR)/$(LIBVORBIS_NAME)-$(LIBVORBIS_VERSION)

.PHONY: extract all

all: extract configure
	@echo "building gstreamer..."
	cd $(LIBVORBIS_TARGET_BUILD_DIR); make
	cd $(LIBVORBIS_TARGET_BUILD_DIR); make install

configure: $(LIBVORBIS_TARGET_BUILD_DIR)/.config

$(LIBVORBIS_TARGET_BUILD_DIR)/.config:
	mkdir -p $(LIBVORBIS_TARGET_BUILD_DIR)
	cd $(LIBVORBIS_TARGET_BUILD_DIR); \
	$(EXTRACT_DIR)/$(LIBVORBIS_NAME)-$(LIBVORBIS_VERSION)/configure \
		PKG_CONFIG_PATH="$(PLATFORM_STAGING_DIR)/lib/pkgconfig" \
		CFLAGS="$(LIBVORBIS_CFLAGS)" \
		LDFLAGS="$(LIBVORBIS_LDFLAGS)" \
		--host=$(TARGET_ARCH) \
		--prefix=$(PLATFORM_STAGING_DIR) 
	touch $@

extract: $(EXTRACT_DIR)/$(LIBVORBIS_NAME)-$(LIBVORBIS_VERSION)

$(EXTRACT_DIR)/$(LIBVORBIS_NAME)-$(LIBVORBIS_VERSION):
	mkdir -p $(EXTRACT_DIR)/$(LIBVORBIS_NAME)-$(LIBVORBIS_VERSION)
	xz -dc $(LIBVORBIS_PKG) | tar xvf - -C $(EXTRACT_DIR)

