-include ./configs/$(TARGET_PLATFORM_NAME)-variables.mk


GLIBNETWORK_NAME := glib-networking
GLIBNETWORK_PKG := src/$(GLIBNETWORK_NAME)-$(GLIBNETWORK_VERSION).tar.xz

GLIBNETWORK_TARGET_BUILD_DIR := $(PLATFORM_BUILD_DIR)/$(GLIBNETWORK_NAME)-$(GLIBNETWORK_VERSION)
GLIBNETWORK_CFLAGS := -I$(PLATFORM_STAGING_DIR)/include
GLIBNETWORK_LDFLAGS := -L$(PLATFORM_STAGING_DIR)/lib


.PHONY: extract all

all: extract configure
	@echo "building glib-networking..."
	cd $(GLIBNETWORK_TARGET_BUILD_DIR); make
	cd $(GLIBNETWORK_TARGET_BUILD_DIR); make install

configure: $(GLIBNETWORK_TARGET_BUILD_DIR)/.config

$(GLIBNETWORK_TARGET_BUILD_DIR)/.config:
	mkdir -p $(GLIBNETWORK_TARGET_BUILD_DIR)
	cd $(GLIBNETWORK_TARGET_BUILD_DIR); \
	$(EXTRACT_DIR)/$(GLIBNETWORK_NAME)-$(GLIBNETWORK_VERSION)/configure \
		PKG_CONFIG_PATH="$(PLATFORM_STAGING_DIR)/lib/pkgconfig" \
		CFLAGS="$(GLIBNETWORK_CFLAGS)" \
		LDFLAGS="$(GLIBNETWORK_LDFLAGS)" \
		--host=$(TARGET_ARCH) \
		--prefix=$(PLATFORM_STAGING_DIR) 
	touch $@

extract: $(EXTRACT_DIR)/$(GLIBNETWORK_NAME)-$(GLIBNETWORK_VERSION)

$(EXTRACT_DIR)/$(GLIBNETWORK_NAME)-$(GLIBNETWORK_VERSION):
	mkdir -p $(EXTRACT_DIR)/$(GLIBNETWORK_NAME)-$(GLIBNETWORK_VERSION)
	xz -dc $(GLIBNETWORK_PKG) | tar xvf - -C $(EXTRACT_DIR)

