#!/bin/bash

TARGET_ARCH=
TARGET_PLATFORM_NAME=

META_FILE= 

USER_HOME_DIR=`dirname ~`/$USER
HOST_STAGING_DIR=$USER_HOME_DIR/work/gst_x86
TARGET_STAGING_DIR=$USER_HOME_DIR/work/target
HOST_BUILD_DIR=`pwd`/host_build
TARGET_BUILD_DIR=`pwd`/target_build
EXTRACT_DIR=`pwd`/unpack
PKG_DIR=`pwd`/packages

TARGET_PLATFORM_NAME_U=
echo -n "Please, Enter a target platform name"
echo " [pioneer, webos-h13]"

read -t 10 TARGET_PLATFORM_NAME_U
if [ -z "$TARGET_TARGET_PLATFORM_NAME_U" ]; then
	TARGET_PLATFORM_NAME=$TARGET_PLATFORM_NAME_U
	META_FILE=`pwd`/configs/$TARGET_PLATFORM_NAME.mk
	if [ -f $META_FILE ]; then
		echo "loading meta data from [$META_FILE]"
		. $META_FILE
	fi
fi

TARGET_STAGING_DIR_U=
echo "Please, Enter a target staging path [$TARGET_STAGING_DIR]"
read -t 10 TARGET_STAGING_DIR_U
if [ -n "$TARGET_STAGING_DIR_U" ]; then
	TARGET_STAGING_DIR=$TARGET_STAGING_DIR_U
	echo "TARGET_STAGING_DIR=$TARGET_STAGING_DIR_U"
fi

echo "detected PLATFORM_CHIP[$PLATFORM_CHIP]"
case $PLATFORM_CHIP in
	lg1154)
		TARGET_ARCH=$TARGET
	;;
	lg115x)
		TARGET_ARCH=$TARGET
	;;
esac

USER_SPECIFIED_MK=`pwd`/configs/$TARGET_PLATFORM_NAME-variables.mk
echo "[$USER_SPECIFIED_MK]"


TARGET_BUILD_DIR=$TARGET_BUILD_DIR/$TARGET_PLATFORM_NAME
TARGET_STAGING_DIR=$TARGET_STAGING_DIR/$TARGET_PLATFORM_NAME

cat `pwd`/configs/$TARGET_PLATFORM_NAME.mk > $USER_SPECIFIED_MK

cat << EOF >> $USER_SPECIFIED_MK

TARGET_PLATFORM_NAME := $TARGET_PLATFORM_NAME
TARGET_STAGING_DIR := $TARGET_STAGING_DIR
TARGET_ARCH := $TARGET_ARCH
TARGET_CC := $TARGET_ARCH-gcc
TARGET_CPP := $TARGET_ARCH-g++
USER_SPECIFIED_MK := $USER_SPECIFIED_MK
HOST_BUILD_DIR := $HOST_BUILD_DIR
TARGET_BUILD_DIR := $TARGET_BUILD_DIR
EXTRACT_DIR := $EXTRACT_DIR
PKG_DIR := $PKG_DIR
HOST_STAGING_DIR := $HOST_STAGING_DIR
TARGET_STAGING_DIR := $TARGET_STAGING_DIR
PLATFORM_BUILD_DIR := \$(TARGET_BUILD_DIR)/\$(PLATFORM_CHIP)
PLATFORM_STAGING_DIR := \$(TARGET_STAGING_DIR)/\$(PLATFORM_CHIP)
EOF

echo "please, set environmental variables"
echo ""
echo "   export TARGET_PLATFORM_NAME=$TARGET_PLATFORM_NAME"
