#!/bin/bash

TARGET_ARCH=


USER_HOME_DIR=`dirname ~`/$USER
HOST_STAGING_DIR=$USER_HOME_DIR/work/gst_x86
TARGET_STAGING_DIR=$USER_HOME_DIR/work/target
HOST_BUILD_DIR=`pwd`/host_build
TARGET_BUILD_DIR=`pwd`/target_build
EXTRACT_DIR=`pwd`/unpack
PKG_DIR=`pwd`/packages

USER_SPECIFIED_MK=`pwd`/configs/$PLATFORM_CHIP-variables.mk

case $PLATFORM_CHIP in
	lg1154)
		TARGET_ARCH=$TARGET
	;;
esac

TARGET_PLATFORM_NAME=pioneer
echo "Please, Enter a target platform name [$TARGET_PLATFORM_NAME]"
read -t 3 TARGET_PLATFORM_NAME_U
if [ x$TARGET_TARGET_PLATFORM_NAME_U != "x" ]; then
	TARGET_PLATFORM_NAME=$TARGET_PLATFORM_NAME_U
fi

echo "Please, Enter a target staging path [$TARGET_STAGING_DIR]"
read -t 3 TARGET_STAGING_DIR_U
if [ x$TARGET_STAGING_DIR_U != "x" ]; then
	TARGET_STAGING_DIR=$TARGET_STAGING_DIR_U
fi

TARGET_BUILD_DIR=$TARGET_BUILD_DIR/$TARGET_PLATFORM_NAME
TARGET_STAGING_DIR=$TARGET_STAGING_DIR/$TARGET_PLATFORM_NAME

HOST_BUILD_DIR=$HOST_BUILD_DIR/$TARGET_PLATFORM_NAME
HOST_STAGING_DIR=$HOST_STAGING_DIR/$TARGET_PLATFORM_NAME

cat << EOF > $USER_SPECIFIED_MK
TARGET_PLATFORM_NAME := $TARGET_PLATFORM_NAME
TARGET_STAGING_DIR := $TARGET_STAGING_DIR
TARGET_ARCH := $TARGET_ARCH
TARGET_CC := $TARGET_ARCH-gcc
TARGET_CPP := $TARGET_ARCH-g++
USER_SPECIFIED_MK := $USER_SPECIFIED_MK
HOST_BUILD_DIR := $HOST_BUILD_DIR
TARGET_BUILD_DIR := $TARGET_BUILD_DIR
EXTRACT_DIR := $EXTRACT_DIR
PKG_DIR := $PKG_DIR
HOST_STAGING_DIR := $HOST_STAGING_DIR
TARGET_STAGING_DIR := $TARGET_STAGING_DIR
PLATFORM_BUILD_DIR := \$(TARGET_BUILD_DIR)/\$(PLATFORM_CHIP)
PLATFORM_STAGING_DIR := \$(TARGET_STAGING_DIR)/\$(PLATFORM_CHIP)
EOF

cat `pwd`/configs/$TARGET_PLATFORM_NAME.mk >> $USER_SPECIFIED_MK
